### ISSUE TITLE
Best way to include only specific extensions?

### ISSUE THREAD

**Issue by gnilrets** [irongaze/iron-extensions#1]
So, I really like DslProxy and am considering using it for a project rather than rolling my own.  However, I'm not sure I want all of the other core extensions that come with this gem.  Do you have any recommended way for just including that component?  My only thought is to just copy that file into my project's repo, but that feels a bit like stealing (despite the very open license).

**Comment by irongaze** [comment]
The DSL stuff was extracted into my iron-dsl gem a bit ago.  That should do it for you I think.  Let me know how you like working with it, and if you have any comments or improvement suggestions.  :-)
